name: wedevs
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  sizer: ^2.0.15
  http: ^1.1.0
  flutter_smart_dialog: ^4.9.7+6
  google_fonts: ^6.1.0
  get_storage: ^2.1.1
  loading_animation_widget: ^1.2.1
  flutter_svg_provider: ^1.0.6
  flutter_svg: ^2.0.10+1
  badges: ^3.1.2
  flutter_native_splash: ^2.3.7
  animated_bottom_navigation_bar: ^1.3.3
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  mobkit_dashed_border: ^0.0.6
  expandable: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
# -------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/

# Run Commend to generate splash screen
# 1) flutter clean
# 1) flutter pub get
# 1) flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png
  android_12:
    image: assets/splash.png

